#################### mlPipe - R package to automate machine learning functions in R ######################
#################### Matheus Maciel Alcantara Salles #####################################################
#################### PPGZoologia UFPR  ###################################################################
#################### Zoology Department ##################################################################

## Msc. Matheus Maciel Alcantara Salles - PPGZoo - UFPR
## matheusmaciel.salles@gmail.com

### Upload packages
library(usethis)
library(devtools)
library(caret)
library(mlbench)

# if you want to create a project
usethis::create_project("C:/Users/mathe/OneDrive/mlPipe")
# if you want to crate a package
usethis::create_package("C:/Users/mathe/OneDrive/mlPipe")

### Adding git to the project
usethis::use_git()
# choose if you want to commit your files.
# If yes: Yup

# choose the best option to restart RStudio


### Config GitHub in your project,
# You´re going to create a repository in your account
# arguments private and visibility to modify repository's visibility
usethis::use_github()
# repository created!

## Some warnings
# Get a situation report on your current Git/GitHub status.
# Useful for diagnosing problems.
usethis::git_sitrep()

# Vaccinate your global gitignore file
# Adds .DS_Store, .Rproj.user, .Rdata, .Rhistory, and .httr-oauth to your
# global (a.k.a. user-level) .gitignore. This is good practice as it
# decreases the chance that you will accidentally leak credentials to GitHub
usethis::git_vaccinate()

### Adding important files ---------------------------------
## Create a README.md file
usethis::use_readme_md()
# You have do edit and then save your README file.
# commit it and then push it to your GitHub profile

### Ignore git files ---------------------------------
usethis::use_git_ignore(c("proj_setup/"))

# R is GPL, any work linking dynamically or statically to R would have to be GPL-based also
# licensas de pacotes permitidas no CRAN:
# https://www.r-project.org/Licenses/
# AGPL, GPLv2, GPLv3, MIT, Creative Commons, Artistic License, etc.

## By now we're going to use GPL
use_gpl3_license()



### Document you functions: help page
# Wouldn't it be nice to access a function's help page, the same way we do with functions in other packages?

# For this you need a special file, which contains all the information:
# man/1-data.config.Rd

# In order to create such files, we need to:
# 1. open your R file: 1-data.config.R
# 2. on your RStudio menu: Code>Insert roxygen skeleton (Ctrl+Alt+Shift+R)
# 3. Write the template according to your need:
{
  #' Configure input data
  #'
  #' @param dataset a dataframe
  #' @param train_percent numerical value (percentage, in decimals) you want for training data
  #' @param resampling
  #'
  #' @return list
  #' @export
  #'
  #' @examples
}

# 4. document your function with:
document()

# See that the documentation was automatically created: arquivos .Rd
# The @export argument in the comments exports the function to the user by updating the NAMESPACE
# You will see something like:
# # Generated by roxygen2: do not edit by hand
#
# export(1-data.confg)

### Check if everything is working again
check()
# If everything is ok, no errors, warnings or notes should appear

### Install
# Since we have a minimally viable package, let's install
install()
devtools::install_github("sallesmath/mlPipe")

# loading and using package
# data(PimaIndiansDiabetes)
# my_df <- PimaIndiansDiabetes
# my_df_config <- data.config(my_df, 0.7, "repeatedcv")
# my_df_config

## Hope everything is working ;)
